version: "3.18"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: transitclock
      POSTGRES_DB: STPT
    ports:
      - "5432:5432"
  gtfsrt-validator:
    image: ghcr.io/mobilitydata/gtfs-realtime-validator:latest
    ports:
      - "9090:8080"
#  transitclock:
#    image: otrro/transitclock-server:latest
#    depends_on:
#      - db
#    environment:
#      AGENCYID: ro.stpt
#      AGENCYNAME: STPT
#      GTFS_URL: https://data.opentransport.ro/routing/gtfs/gtfs-stpt.zip
#      GTFSRTVEHICLEPOSITIONS: https://api.opentransport.ro/exporter/v1/realtime/stpt/vehicle-positions
#      PGPASSWORD: transitclock
#      POSTGRES_PORT_5432_TCP_ADDR: db
#      POSTGRES_PORT_5432_TCP_PORT: 5432
#
#    ports:
#      - "8080:8080"
#    command:
#      - --gtfs-url
#      - https://data.opentransport.ro/routing/gtfs/gtfs-stpt.zip